import type { SideContent } from './types';

export const digital: SideContent = {
  key: 'digital',
  name: 'Digital Solutions',
  path: '/digital',
  nav: [
    { label: 'Home', to: '/digital' },
    { label: 'About', to: '/digital/about' },
    { label: 'Services', to: '/digital/services' },
    { label: 'Work', to: '/digital/work' },
    { label: 'Reviews', to: '/digital/reviews' },
    { label: 'Contact', to: '/digital/contact' },
  ],
  heroEyebrow: 'Digital Solutions',
  welcome: 'Websites, stores, and web apps for your business, built, launched, and supported long after go-live.',
  heroHeadline: ['Websites and apps', 'that keep working.'],
  heroSub:
    'We design, build, and maintain websites, ecommerce stores, dashboards, and custom business systems, then stay on to update and support them.',
  primary: { label: 'Start a project', to: '/digital/contact' },
  secondary: { label: 'See our services', to: '/digital/services' },

  problem: {
    label: 'The gap',
    title: 'Good ideas shouldn’t stay unfinished.',
    sub: 'Most business ideas don’t fail on vision. They stall between the plan and a working product people can actually use.',
    cards: [
      {
        title: 'Ideas stay stuck as slides',
        body: 'A plan on paper doesn’t take orders or book customers. We turn it into a live site or app with real screens and real flows.',
      },
      {
        title: 'Deadlines move faster than DIY',
        body: 'Template builders and part-time help slip. We scope first, build in clear stages, and tell you what ships when.',
      },
      {
        title: 'Support disappears after delivery',
        body: 'A site goes stale the week after launch. We handle updates, content, bug fixes, and hosting once it’s live.',
      },
    ],
  },

  services: {
    label: 'Services',
    title: 'What we build for you.',
    sub: 'Four ways to start. Pick what’s holding your business back most.',
    pageTitle: 'Eight ways we help.',
    pageSub: 'Every engagement is scoped around your business. Start with the one that fits, we’ll grow from there.',
    items: [
      {
        id: 'website',
        icon: 'globe',
        title: 'Custom Website Development',
        short: 'Modern, responsive, SEO-friendly websites for businesses, personal brands, institutions, and service providers.',
        outcome: 'A credible online home for your business.',
        included: [
          'Page structure and content plan',
          'Responsive design for phone, tablet, and desktop',
          'SEO basics: titles, descriptions, fast loading',
          'Contact forms and WhatsApp links',
          'Deployment to your domain',
        ],
        bestFor: 'Businesses that rely on word of mouth and need a professional presence customers can find and trust.',
        outcomes: ['A site you’re proud to share', 'Customers can reach you in one tap', 'Content you can ask us to update anytime'],
        useCases: ['Local business landing site', 'Personal brand portfolio', 'Institution or clinic information site', 'Service provider with booking enquiries'],
        cta: 'Plan my website',
      },
      {
        id: 'webapp',
        icon: 'layers',
        title: 'Web Application Development',
        short: 'Custom dashboards, admin panels, booking systems, portals, and business tools built around your workflow.',
        outcome: 'Software shaped around how you already work.',
        included: [
          'Workflow mapping before any code',
          'Frontend in React and TypeScript',
          'Backend in Spring Boot with MySQL when data must be stored',
          'Login and role-based access where needed',
          'Admin dashboard to manage everything',
        ],
        bestFor: 'Teams running on spreadsheets, chat threads, or paper registers that have outgrown them.',
        outcomes: ['One place for your records', 'Less manual re-entry', 'A system your team can actually learn'],
        useCases: ['Student and fee management', 'Appointment and booking portal', 'Inventory and order tracker', 'Internal approvals dashboard'],
        cta: 'Scope my application',
      },
      {
        id: 'ecommerce',
        icon: 'cart',
        title: 'Ecommerce Solutions',
        short: 'Move from WhatsApp-only selling to a professional store with product showcase, orders, and customer flow.',
        outcome: 'Orders that arrive organised, not scattered.',
        included: [
          'Product catalogue and categories',
          'Cart and order flow',
          'Order handoff to WhatsApp or email',
          'Admin tools for stock and pricing',
          'Mobile-first storefront',
        ],
        bestFor: 'Boutiques and small sellers who take orders by message today and want a store customers can browse.',
        outcomes: ['A browsable catalogue', 'Fewer missed orders', 'Easier stock and price updates'],
        useCases: ['Boutique collection showcase', 'Home business product catalogue', 'Local retail store online', 'Order enquiries redirected to WhatsApp'],
        cta: 'Plan my store',
      },
      {
        id: 'uiux',
        icon: 'palette',
        title: 'UI/UX Design',
        short: 'Clean, conversion-focused interfaces that make your website easy to use and professional to present.',
        outcome: 'An interface people understand at a glance.',
        included: ['User flow and page structure', 'Visual direction and colour system', 'Typography and spacing rules', 'Responsive layouts', 'Design handoff into build'],
        bestFor: 'Anyone whose product works but looks, or feels, unfinished.',
        outcomes: ['A consistent visual identity', 'Clearer calls to action', 'A design ready to build from'],
        useCases: ['Redesign of an outdated site', 'Design for a new app idea', 'Landing page for a campaign', 'Dashboard layout cleanup'],
        cta: 'Talk about design',
      },
      {
        id: 'maintenance',
        icon: 'wrench',
        title: 'Website Maintenance',
        short: 'We update products, stock, content, banners, designs, pages, and business information whenever needed.',
        outcome: 'A site that never goes stale.',
        included: ['Content and banner updates', 'Product and stock changes', 'Page edits and new pages', 'Small design refreshes', 'Business information changes'],
        bestFor: 'Owners who don’t have time to touch the site but need changes made quickly.',
        outcomes: ['Updates handled for you', 'Accurate information online', 'No waiting on a stranger freelancer'],
        useCases: ['Seasonal banner changes', 'Weekly stock updates', 'New service page', 'Contact detail changes'],
        cta: 'Set up maintenance',
      },
      {
        id: 'server',
        icon: 'server',
        title: 'Server & Technical Support',
        short: 'Deployment support, hosting guidance, server monitoring, bug fixes, and long-term technical assistance.',
        outcome: 'Someone technical who answers when it breaks.',
        included: ['Deployment support', 'Hosting guidance', 'Server monitoring', 'Bug fixes', 'Long-term technical assistance'],
        bestFor: 'Businesses with an existing site or app and no technical person on the team.',
        outcomes: ['Faster fixes', 'Fewer surprise outages', 'Clear advice on hosting choices'],
        useCases: ['Moving a site to new hosting', 'Fixing a broken form', 'Monitoring a live application', 'Help with a domain or SSL issue'],
        cta: 'Get technical help',
      },
      {
        id: 'automation',
        icon: 'workflow',
        title: 'Business Automation',
        short: 'Simple digital systems that reduce manual work, organise leads, manage orders, and improve customer communication.',
        outcome: 'Less repetitive work for your team.',
        included: ['Process review', 'Lead capture and tracking', 'Order management flow', 'Customer message handling', 'Reports from your data'],
        bestFor: 'Teams repeating the same steps every day who want those steps handled by a system.',
        outcomes: ['Fewer manual tasks', 'Leads tracked in one place', 'Faster replies to customers'],
        useCases: ['Enquiry form to lead list', 'Order status updates', 'Daily report generation', 'Customer follow-up reminders'],
        cta: 'Find what to automate',
      },
      {
        id: 'assistance',
        icon: 'headphones',
        title: '24/7 Assistance Plans',
        short: 'Ongoing support plans for clients who want continuous improvements, maintenance, and quick help.',
        outcome: 'Quick help, whenever you need it.',
        included: ['Priority support channel', 'Continuous improvements', 'Regular maintenance', 'Quick-turnaround fixes', 'A single point of contact'],
        bestFor: 'Businesses whose website or app is part of daily operations.',
        outcomes: ['A fast response path', 'Steady improvement', 'Peace of mind'],
        useCases: ['Online store during peak season', 'Booking app used daily', 'Institution portal', 'Any site that can’t be down'],
        cta: 'Ask about plans',
      },
    ],
    matchTitle: 'Match your need to the right service.',
    match: [
      { need: 'You sell on WhatsApp only', start: 'Ecommerce Solutions' },
      { need: 'You need a site that looks credible', start: 'Custom Website Development' },
      { need: 'Your team runs on spreadsheets and chats', start: 'Web Application Development' },
      { need: 'Your site is live but outdated', start: 'Website Maintenance' },
    ],
  },

  audience: {
    label: 'Who we serve',
    title: 'Built for your kind of business.',
    sub: 'Entrepreneurs, local businesses, boutiques, institutions, and service providers.',
    rows: [
      { title: 'Local Businesses', body: 'Shops, studios, and service counters that need to be found online and contacted easily.', icon: 'store' },
      { title: 'Boutiques & Retail', body: 'Collections, catalogues, and WhatsApp ordering turned into an organised store.', icon: 'sparkles' },
      { title: 'Entrepreneurs', body: 'First products and early ideas that need a working version before anything else.', icon: 'rocket' },
      { title: 'Institutions', body: 'Schools and colleges that need records, fees, attendance, and an admin view.', icon: 'building' },
      { title: 'Service Providers', body: 'Consultants and clinics who need bookings, enquiries, and a trusted online profile.', icon: 'briefcase' },
    ],
  },

  progress: {
    label: 'Our progress',
    title: 'From idea to live, step by step.',
    sub: 'Five stages, each tied to a service we deliver. Scroll to move through them.',
    steps: [
      { icon: 'lightbulb', title: 'Share your idea', body: 'We understand your business, goal, customers, and the features you need before anything else.' },
      { icon: 'palette', title: 'Plan and design', body: 'We prepare the structure, user flow, pages, and visual direction for your project.' },
      { icon: 'code', title: 'Build', body: 'We develop the site or application in clear stages, so you see progress and can steer it.' },
      { icon: 'rocket', title: 'Launch', body: 'We test, deploy, and make it ready for real users and real business.' },
      { icon: 'headphones', title: 'Maintain and grow', body: 'We support updates, improvements, products, content, and technical maintenance on an ongoing basis.' },
    ],
  },

  work: {
    label: 'Selected work',
    title: 'What we’ve built and designed.',
    sub: 'Delivered systems and concept work that show the range of what we can create for you.',
    pageTitle: 'Projects, delivered and in concept.',
    pageSub: 'One delivered full stack system and four concept builds. Concepts are labelled so you always know which is which.',
    items: [
      {
        id: 'university',
        tag: 'Education / Institutional Software',
        kind: 'Full stack system',
        headline: 'Smart University Management System',
        summary:
          'A full stack platform covering student records, attendance, exams, fee tracking, faculty workload, and an admin dashboard. Built and delivered end to end.',
        tech: ['React', 'Spring Boot', 'MySQL', 'Admin Dashboard'],
        status: 'Completed',
        seed: 3,
        image: 'DS1',
        problem: 'Institutions keep student, fee, and exam records in separate registers and sheets, which makes reporting slow and error-prone.',
        approach: ['Mapped student, faculty, and admin workflows', 'Built the React frontend with a Spring Boot and MySQL backend', 'Added an admin dashboard to manage every module'],
        results: ['Student records, attendance, exams, and fees in one system', 'Faculty workload tracking', 'Admin dashboard for management'],
      },
      {
        id: 'boutique',
        tag: 'Fashion / Local Business',
        kind: 'Concept website',
        headline: 'Boutique Business Website',
        summary: 'A premium website concept for boutiques to showcase collections and send customers to WhatsApp to order.',
        tech: ['React', 'TypeScript', 'UI/UX', 'WhatsApp'],
        status: 'Concept / Demo',
        seed: 7,
        image: 'DS2',
        problem: 'Boutiques sell through chat threads, so customers never see a full collection in one place.',
        approach: ['Designed a collection-first layout', 'Added product enquiry links that open WhatsApp', 'Kept the page fast on mobile'],
        results: ['Concept shows how a catalogue can replace scattered photos', 'One-tap WhatsApp enquiry flow'],
      },
      {
        id: 'guidance',
        tag: 'Education / Student Services',
        kind: 'Concept platform',
        headline: 'Academic Project Guidance Platform',
        summary: 'A platform concept for students to explore final-year project ideas across Embedded, IoT, AI/ML, and Robotics and request end-to-end support.',
        tech: ['React', 'Dashboard', 'UI/UX', 'Student Services'],
        status: 'Concept / Demo',
        seed: 11,
        image: 'DS3',
        problem: 'Students struggle to find a suitable project title and know what support exists.',
        approach: ['Organised titles by department and category', 'Added search, filters, and detail views', 'Connected each title to a direct enquiry'],
        results: ['Concept now powers the Student Lab catalogue on this site'],
      },
      {
        id: 'landing',
        tag: 'Brand Website',
        kind: 'Concept landing page',
        headline: 'Business Landing Page',
        summary: 'A modern landing page structure for local businesses to present services, contact details, and lead forms.',
        tech: ['Landing Page', 'SEO', 'Responsive Design'],
        status: 'Concept / Demo',
        seed: 5,
        problem: 'Small businesses need a single page that explains what they do and makes contact easy.',
        approach: ['Defined a clear section order', 'Added a lead form and contact buttons', 'Optimised titles and descriptions for search'],
        results: ['Reusable structure for local business pages'],
      },
      {
        id: 'catalog',
        tag: 'Online Store',
        kind: 'Concept store',
        headline: 'Ecommerce Product Showcase',
        summary: 'A product-focused layout for businesses moving from WhatsApp selling to an organised online catalogue.',
        tech: ['Ecommerce', 'Product Catalog', 'WhatsApp Orders'],
        status: 'Concept / Demo',
        seed: 9,
        problem: 'Orders taken over chat are hard to track and customers can’t browse.',
        approach: ['Built a product grid with categories', 'Designed a simple order handoff', 'Planned admin tools for stock'],
        results: ['Concept for an organised catalogue and order flow'],
      },
    ],
  },

  reviews: {
    label: 'What clients say',
    title: 'Don’t take our word for it.',
    sub: 'Placeholder reviews, clearly marked. Real client reviews replace these as they arrive.',
    items: [
      { id: 1, quote: 'Professional design approach and clear, consistent communication throughout the entire project.', name: 'Business Client', role: 'Local Business Owner', initial: 'B', sample: true },
      { id: 2, quote: 'The website made our business presentation look far more trustworthy and professional online.', name: 'Boutique Owner', role: 'Fashion and Retail', initial: 'F', sample: true },
      { id: 3, quote: 'Quick updates and solid technical support. They respond fast and deliver what they promise.', name: 'Store Owner', role: 'Ecommerce Business', initial: 'S', sample: true },
    ],
  },

  about: {
    heroTitle: 'The story behind Tuning Ideas.',
    heroSub: 'A full stack development and digital solutions brand that helps businesses move from a simple online presence to powerful digital systems.',
    storyLabel: 'Our story',
    storyTitle: 'Built to turn ideas into working products.',
    story: [
      'Tuning Ideas helps entrepreneurs, local businesses, boutiques, institutions, and service providers convert ideas into clean, scalable, and user-friendly web applications.',
      'We take a practical, first-principles approach. We understand your goals before writing a single line of code, and every solution is built to work for your real customers and your real deadlines.',
      'We also don’t disappear after launch. Maintenance, server support, and assistance plans are part of how we work.',
    ],
    quote: 'A website is not finished when it launches. That’s when the real work begins.',
    beliefsTitle: 'What we believe.',
    beliefs: [
      { title: 'Understand first', body: 'We learn your business, customers, and goals before we design or code anything.' },
      { title: 'Honest scope', body: 'We tell you what is realistic, and we label concept work as concept work.' },
      { title: 'Built to be maintained', body: 'Clean code and clear structure so changes stay quick and affordable.' },
      { title: 'Stay after launch', body: 'Updates, fixes, and support continue after delivery.' },
    ],
    stats: [
      { value: '8', label: 'Digital services' },
      { value: '4', label: 'Steps from idea to launch' },
      { value: '24/7', label: 'Assistance plans available' },
      { value: '5', label: 'Projects, delivered and in concept' },
    ],
    ctaTitle: 'Have an idea worth building?',
    ctaSub: 'Tell us about it. We’ll reply with honest next steps.',
  },

  faqs: [
    { q: 'Do I need to be technical to work with you?', a: 'No. We explain every step in plain language and handle the technical decisions with you.' },
    { q: 'How long does a website take?', a: 'It depends on scope. After a first conversation we give you a staged timeline so you know what ships when.' },
    { q: 'What does it cost?', a: 'We quote after understanding what you need. There are no fixed packages that force you to pay for features you won’t use.' },
    { q: 'Do you maintain the site after launch?', a: 'Yes. Website maintenance, server support, and 24/7 assistance plans are part of what we offer.' },
    { q: 'What technology do you use?', a: 'React, TypeScript, Node.js, Spring Boot, MySQL, and Tailwind, chosen to fit the project rather than the other way around.' },
  ],

  contact: {
    label: 'Get in touch',
    title: 'Let’s build your idea.',
    sub: 'Tell us about your project. We reply personally.',
    options: ['Website Development', 'Web Application', 'Ecommerce', 'UI/UX Design', 'Maintenance', 'Server Support', 'Other'],
    intro: 'Hi Tuning Ideas, I’d like to discuss a digital project.',
  },

  footerLine: 'Websites and applications that keep working after launch.',
  footerLinks: [
    {
      title: 'Services',
      links: [
        { label: 'Websites', to: '/digital/services' },
        { label: 'Web Applications', to: '/digital/services' },
        { label: 'Ecommerce', to: '/digital/services' },
        { label: 'Maintenance', to: '/digital/services' },
      ],
    },
    {
      title: 'Company',
      links: [
        { label: 'About', to: '/digital/about' },
        { label: 'Work', to: '/digital/work' },
        { label: 'Reviews', to: '/digital/reviews' },
        { label: 'Contact', to: '/digital/contact' },
      ],
    },
  ],
};
